### ISSUE TITLE
py-10 w-full h-screen

### ISSUE THREAD

**Issue by avinahome** [dissorial/pdf-chatbot#2]
needs to be py-10 w-full h-full

It looks so much better in the chat interface.

**Comment by dissorial** [comment]
In what component?

**Comment by avinahome** [comment]
Sorry, I don't know exactly where it is, but it is on the main view-source:http://localhost:3000/namespace/pdf-test

The difference is when you scroll past the first screen of chats, it is either the correct color with py-10 w-full h-full, or it cuts off being blue at the bottom of the screen and is white from there on out.

**Comment by dissorial** [comment]
I'm afraid I can't see what you see on your local network. Nevertheless, the UI was indeed basically broken for chats with messages that extend past the default page height. I updated it so that the screen does not cut off, and the sidebar + user input are for chat remain fixed in place. Try to pull the changes into your repo and see if it's better:)

**Comment by avinahome** [comment]
Excellent!  Thank you so much!
